"""
Django settings for site_hitech project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fx^a=6!1s-s@2&@@n&ko__s5+1&t728&emqnhh&-+j93j_khqa')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'hitechndt.vn,www.hitechndt.vn,localhost,127.0.0.1,192.168.1.4,192.168.1.192,0.0.0.0').split(',')
# Bỏ dòng cũ:
# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'hitechndt.vn,www.hitechndt.vn,localhost,127.0.0.1,192.168.1.4,0.0.0.0').split(',')

# Thay bằng:
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.192', '0.0.0.0', '*']

# Application definition

# Thêm channels vào INSTALLED_APPS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_ckeditor_5',
    
    'django_summernote',
    'colorfield',
    'channels',
]

# Cấu hình ASGI application
ASGI_APPLICATION = 'site_hitech.asgi.application'

# Cấu hình Channel layers
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Thêm WhiteNoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Thêm LocaleMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site_hitech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'api.context_processors.categories',
                'api.context_processors.site_settings',
            ],
        },
    },
]


WSGI_APPLICATION = 'site_hitech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration - Updated for Ubuntu 22.04
db_engine = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')

# Default SQLite for development
default_db = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

# MySQL configuration for production using mysql-connector-python
if db_engine == 'mysql.connector.django' and os.environ.get('DB_NAME'):
    default_db = {
        'ENGINE': 'mysql.connector.django',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }

DATABASES = {
    'default': default_db,
}

# Thêm cấu hình cho báo cáo
REPORT_SETTINGS = {
    'EXPORT_FORMATS': ['pdf', 'excel', 'csv'],
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_EXPORT_RECORDS': 10000,
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Languages
LANGUAGES = [
    ('vi', _('Tiếng Việt')),
    ('en', _('English')),
]

LANGUAGE_CODE = 'vi'
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'error',
}

# WhiteNoise configuration for serving static files in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Bảo mật thêm cho production
    SECURE_HSTS_SECONDS = 31536000  # 1 năm
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_PRELOAD = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration - File-based cache thay vì Redis để tiết kiệm RAM
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
        'TIMEOUT': 3600,  # Cache 1 giờ
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Giới hạn số file cache
            'CULL_FREQUENCY': 3,  # Xóa 1/3 cache khi đạt MAX_ENTRIES
        }
    }
}

# Session configuration - Lưu session vào database thay vì cache/redis
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # Session hết hạn sau 1 ngày

# Cấu hình URL đăng nhập
LOGIN_URL = '/staff/login/'

# Production optimizations
if not DEBUG:
    # Security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Session security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Logging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': '/var/log/django/hitechndt.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }

# Cấu hình CKEditor - Updated với phiên bản LTS tương thích Ubuntu 20.04
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

# Sử dụng CKEditor 4.25.1-lts (tương thích Ubuntu 20.04)
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 400,
        'width': '100%',
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'extraPlugins': ','.join([
            'codesnippet',
        ]),
        'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['NumberedList', 'BulletedList'],
            ['Indent', 'Outdent'],
            ['Maximize'],
            ['CodeSnippet'],
        ],
        'codeSnippet_theme': 'monokai',
        'language': 'vi',
    },
    'awesome_ckeditor': {
        'toolbar': 'Basic',
        'height': 300,
        'width': '100%',
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
    },
}

# Cấu hình Summernote
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'width': '100%',
        'height': '400px',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'italic', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video', 'hr']],
            ['view', ['fullscreen', 'codeview']],
        ],
        'popover': {
            'image': [
                ['image', ['resizeFull', 'resizeHalf', 'resizeQuarter', 'resizeNone']],
                ['float', ['floatLeft', 'floatRight', 'floatNone']],
                ['remove', ['removeMedia']]
            ],
            'link': [
                ['link', ['linkDialogShow', 'unlink']]
            ],
            'table': [
                ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
                ['delete', ['deleteRow', 'deleteCol', 'deleteTable']],
            ],
        },
        'lang': 'vi-VN',
        'codemirror': {
            'theme': 'monokai'
        }
    },
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    ),
    'js': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/xml/xml.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/javascript/javascript.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/css/css.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/htmlmixed/htmlmixed.min.js',
    ),
    'disable_attachment': False,
    'attachment_filesize_limit': 10485760,  # 10MB
    'attachment_require_authentication': True,
    'attachment_upload_to': 'summernote_attachments/%Y/%m/',
}

# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
    },
    'advanced': {
        'toolbar': [
            'heading', '|', 
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'link', 'uploadImage', 'mediaEmbed', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'outdent', 'indent', '|',
            'blockQuote', 'insertTable', '|',
            'code', 'codeBlock', '|',
            'alignment', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Đoạn văn', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Tiêu đề 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Tiêu đề 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Tiêu đề 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Tiêu đề 4', 'class': 'ck-heading_heading4'},
            ]
        },
        'fontSize': {
            'options': [9, 11, 13, 'default', 17, 19, 21, 24, 28],
            'supportAllValues': True
        },
        'fontColor': {
            'colors': [
                {'color': 'hsl(0, 0%, 0%)', 'label': 'Đen'},
                {'color': 'hsl(0, 0%, 30%)', 'label': 'Xám đậm'},
                {'color': 'hsl(0, 0%, 60%)', 'label': 'Xám'},
                {'color': 'hsl(0, 0%, 90%)', 'label': 'Xám nhạt'},
                {'color': 'hsl(0, 0%, 100%)', 'label': 'Trắng'},
                {'color': 'hsl(0, 75%, 60%)', 'label': 'Đỏ'},
                {'color': 'hsl(30, 75%, 60%)', 'label': 'Cam'},
                {'color': 'hsl(60, 75%, 60%)', 'label': 'Vàng'},
                {'color': 'hsl(90, 75%, 60%)', 'label': 'Xanh lá nhạt'},
                {'color': 'hsl(120, 75%, 60%)', 'label': 'Xanh lá'},
                {'color': 'hsl(150, 75%, 60%)', 'label': 'Aquamarine'},
                {'color': 'hsl(180, 75%, 60%)', 'label': 'Turquoise'},
                {'color': 'hsl(210, 75%, 60%)', 'label': 'Xanh nhạt'},
                {'color': 'hsl(240, 75%, 60%)', 'label': 'Xanh dương'},
                {'color': 'hsl(270, 75%, 60%)', 'label': 'Tím'},
                {'color': 'hsl(300, 75%, 60%)', 'label': 'Magenta'},
            ]
        },
        'fontBackgroundColor': {
            'colors': [
                {'color': 'hsl(0, 0%, 0%)', 'label': 'Đen'},
                {'color': 'hsl(0, 0%, 30%)', 'label': 'Xám đậm'},
                {'color': 'hsl(0, 0%, 60%)', 'label': 'Xám'},
                {'color': 'hsl(0, 0%, 90%)', 'label': 'Xám nhạt'},
                {'color': 'hsl(0, 0%, 100%)', 'label': 'Trắng'},
                {'color': 'hsl(0, 75%, 60%)', 'label': 'Đỏ'},
                {'color': 'hsl(30, 75%, 60%)', 'label': 'Cam'},
                {'color': 'hsl(60, 75%, 60%)', 'label': 'Vàng'},
                {'color': 'hsl(90, 75%, 60%)', 'label': 'Xanh lá nhạt'},
                {'color': 'hsl(120, 75%, 60%)', 'label': 'Xanh lá'},
                {'color': 'hsl(150, 75%, 60%)', 'label': 'Aquamarine'},
                {'color': 'hsl(180, 75%, 60%)', 'label': 'Turquoise'},
                {'color': 'hsl(210, 75%, 60%)', 'label': 'Xanh nhạt'},
                {'color': 'hsl(240, 75%, 60%)', 'label': 'Xanh dương'},
                {'color': 'hsl(270, 75%, 60%)', 'label': 'Tím'},
                {'color': 'hsl(300, 75%, 60%)', 'label': 'Magenta'},
            ]
        },
        'alignment': {
            'options': ['left', 'center', 'right', 'justify']
        },
        'image': {
            'toolbar': [
                'imageStyle:inline',
                'imageStyle:block',
                'imageStyle:side',
                '|',
                'toggleImageCaption',
                'imageTextAlternative',
                '|',
                'linkImage'
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableCellProperties',
                'tableProperties'
            ]
        },
        'link': {
            'addTargetToExternalLinks': True
        },
        'codeBlock': {
            'languages': [
                {'language': 'css', 'label': 'CSS'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'php', 'label': 'PHP'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'xml', 'label': 'XML'},
            ]
        }
    }
}

# Email (SMTP) configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@hitechndt.vn')
