# Generated by Django 5.1.7 on 2025-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coursecategory_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email người nhận')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone_numbers', models.TextField(help_text='Mỗi số điện thoại một dòng', verbose_name='Số điện thoại')),
                ('business_hours', models.TextField(help_text='Định dạng: Thứ Hai - Thứ Sáu: 8:00 - 17:30', verbose_name='Giờ làm việc')),
                ('email_contact', models.TextField(help_text='Mỗi email một dòng', verbose_name='Email liên hệ')),
                ('maps_embed', models.TextField(help_text='Mã iframe từ Google Maps', verbose_name='Mã nhúng Google Maps')),
            ],
            options={
                'verbose_name': 'Cấu hình liên hệ',
                'verbose_name_plural': 'Cấu hình liên hệ',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
    ]
