# Generated by Django 5.1.7 on 2025-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactsettings_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_bg_color', models.CharField(default='#212529', max_length=20, verbose_name='Màu nền Navbar')),
                ('navbar_text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Màu chữ Navbar')),
                ('navbar_brand_size', models.CharField(default='1.8rem', max_length=10, verbose_name='Kích thước chữ thương hiệu')),
                ('navbar_link_size', models.CharField(default='1.2rem', max_length=10, verbose_name='Kích thước chữ menu')),
                ('footer_bg_color', models.CharField(default='#212529', max_length=20, verbose_name='Màu nền Footer')),
                ('footer_text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Màu chữ Footer')),
                ('footer_link_color', models.CharField(default='#6c757d', max_length=20, verbose_name='Màu liên kết Footer')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo công ty')),
                ('company_name', models.CharField(default='Hitech NDT', max_length=100, verbose_name='Tên công ty')),
                ('company_slogan', models.CharField(default='Giải pháp công nghệ hàng đầu', max_length=200, verbose_name='Slogan công ty')),
                ('company_description', models.TextField(default='Hitech NDT tự hào là đơn vị hàng đầu trong lĩnh vực kiểm tra không phá hủy và đào tạo chứng chỉ NDT tại Việt Nam', verbose_name='Mô tả công ty')),
                ('footer_address', models.CharField(default='123 Đường ABC, Quận XYZ, TP.HCM', max_length=200, verbose_name='Địa chỉ')),
                ('footer_phone', models.CharField(default='+84 123 456 789', max_length=20, verbose_name='Số điện thoại')),
                ('footer_email', models.EmailField(default='info@hitechndt.com', max_length=254, verbose_name='Email')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
            ],
            options={
                'verbose_name': 'Cấu hình website',
                'verbose_name_plural': 'Cấu hình website',
            },
        ),
    ]
