# Generated by Django 5.1.7 on 2025-04-11 11:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_color',
            field=colorfield.fields.ColorField(default='#003d99', image_field=None, max_length=25, samples=None, verbose_name='Màu nền Hero Section (khi không có hình)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hình nền Hero Section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn_primary_text',
            field=models.CharField(default='Khám phá dịch vụ', max_length=50, verbose_name='Nút chính - Văn bản'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn_primary_url',
            field=models.CharField(default='/dich-vu', max_length=100, verbose_name='Nút chính - Liên kết'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn_secondary_text',
            field=models.CharField(default='Liên hệ ngay', max_length=50, verbose_name='Nút phụ - Văn bản'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn_secondary_url',
            field=models.CharField(default='/lien-he', max_length=100, verbose_name='Nút phụ - Liên kết'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hình ảnh Hero Section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Công nghệ kiểm tra không phá hủy hàng đầu Việt Nam với các giải pháp tiên tiến và đội ngũ chuyên gia giàu kinh nghiệm', verbose_name='Mô tả Hero Section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='HITECH NDT', max_length=100, verbose_name='Tiêu đề Hero Section'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Màu nền Footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_link_color',
            field=colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None, verbose_name='Màu liên kết Footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ Footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Màu nền Navbar'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_brand_size',
            field=models.CharField(default='18px', max_length=10, verbose_name='Kích thước chữ thương hiệu (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_link_size',
            field=models.CharField(default='14px', max_length=10, verbose_name='Kích thước chữ menu (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ Navbar'),
        ),
    ]
