# Generated by Django 5.1.7 on 2025-05-26 02:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitesettings_hero_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Giới thiệu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(default='Hitech NDT là đơn vị hàng đầu trong lĩnh vực kiểm tra không phá hủy tại Việt Nam. Với đội ngũ kỹ sư giàu kinh nghiệm và trang thiết bị hiện đại, chúng tôi cam kết mang đến những dịch vụ chất lượng cao nhất.', verbose_name='Nội dung phần Giới thiệu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Hình ảnh phần Giới thiệu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='Tại sao chọn Hitech NDT?', max_length=100, verbose_name='Tiêu đề phần Giới thiệu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_logo1',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Logo đối tác 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_logo2',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Logo đối tác 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_logo3',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Logo đối tác 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_logo4',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Logo đối tác 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_logo5',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Logo đối tác 5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_logo6',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Logo đối tác 6'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='clients_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Đối tác'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='clients_title',
            field=models.CharField(default='Đối tác của chúng tôi', max_length=100, verbose_name='Tiêu đề phần Đối tác'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Dự án'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả phần Dự án'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_title',
            field=models.CharField(default='Dự án tiêu biểu', max_length=100, verbose_name='Tiêu đề phần Dự án'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(default='Dịch vụ chuyên nghiệp', max_length=100, verbose_name='Tiêu đề phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Đánh giá'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_title',
            field=models.CharField(default='Khách hàng nói gì về chúng tôi', max_length=100, verbose_name='Tiêu đề phần Đánh giá'),
        ),
    ]
