# Generated by Django 5.1.7 on 2025-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_options_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'Người dùng'), ('ADMIN', 'Quản trị viên'), ('AUTO', 'Tự động')], max_length=5)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply_message', models.TextField(default='Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi sớm nhất có thể.', verbose_name='Tin nhắn tự động trả lời')),
                ('zalo_phone', models.CharField(max_length=15, verbose_name='Số điện thoại Zalo')),
                ('is_chat_enabled', models.BooleanField(default=True, verbose_name='Bật/tắt chat')),
            ],
            options={
                'verbose_name': 'Cấu hình chat',
                'verbose_name_plural': 'Cấu hình chat',
            },
        ),
    ]
