# Generated by Django 5.1.7 on 2025-06-05 01:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatmessage_chatsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề trang')),
                ('banner_image', models.ImageField(upload_to='about/', verbose_name='Ảnh banner')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Nội dung')),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tầm nhìn')),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sứ mệnh')),
                ('core_values', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giá trị cốt lõi')),
                ('achievements', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Thành tựu')),
                ('team_section_title', models.CharField(default='Đội ngũ của chúng tôi', max_length=200, verbose_name='Tiêu đề phần đội ngũ')),
                ('team_section_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả phần đội ngũ')),
                ('certificates_section_title', models.CharField(default='Chứng chỉ & Giấy phép', max_length=200, verbose_name='Tiêu đề phần chứng chỉ')),
                ('certificates', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Danh sách chứng chỉ')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Trang giới thiệu',
                'verbose_name_plural': 'Trang giới thiệu',
            },
        ),
    ]
