# Generated by Django 5.1.7 on 2025-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Phụ đề hiển thị bên dưới tiêu đề chính', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='Về Chúng Tôi', max_length=200),
        ),
    ]
