# Generated by Django 5.1.7 on 2025-06-05 03:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aboutpage_subtitle_alter_aboutpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='timeline',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Nhập theo format: Năm|Tiêu đề|Mô tả, mỗi cột mốc một dòng', null=True, verbose_name='Cột mốc thời gian'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_section_title',
            field=models.CharField(default='Cột mốc phát triển', max_length=200, verbose_name='Tiêu đề phần cột mốc'),
        ),
    ]
