# Generated by Django 5.1.7 on 2025-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_aboutpage_timeline_aboutpage_timeline_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='timeline',
            field=models.TextField(blank=True, help_text='Nhập theo format: Năm|Tiêu đề|Mô tả, mỗi cột mốc một dòng', null=True, verbose_name='Cột mốc thời gian'),
        ),
    ]
