# Generated by Django 5.1.7 on 2025-06-06 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_aboutpage_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('manager', 'Quản lý'), ('staff', 'Nhân viên')], default='staff', max_length=20, verbose_name='Vai trò')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phòng ban')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Giới thiệu')),
                ('can_create_posts', models.BooleanField(default=True, verbose_name='Có thể tạo bài viết')),
                ('can_edit_all_posts', models.BooleanField(default=False, verbose_name='Có thể chỉnh sửa tất cả bài viết')),
                ('can_delete_posts', models.BooleanField(default=False, verbose_name='Có thể xóa bài viết')),
                ('can_publish_posts', models.BooleanField(default=False, verbose_name='Có thể xuất bản bài viết')),
                ('can_create_courses', models.BooleanField(default=True, verbose_name='Có thể tạo khóa học')),
                ('can_edit_all_courses', models.BooleanField(default=False, verbose_name='Có thể chỉnh sửa tất cả khóa học')),
                ('can_delete_courses', models.BooleanField(default=False, verbose_name='Có thể xóa khóa học')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Có thể quản lý người dùng')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='Có thể xem thống kê')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Có thể quản lý cài đặt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
