# Generated by Django 5.1.7 on 2025-06-08 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã công ty')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thiết bị')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Số serial')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Nhà sản xuất')),
                ('calibration_date', models.DateField(verbose_name='Ngày hiệu chuẩn')),
                ('next_calibration', models.DateField(verbose_name='Ngày hiệu chuẩn tiếp theo')),
                ('status', models.CharField(choices=[('active', 'Đang sử dụng'), ('maintenance', 'Bảo trì'), ('retired', 'Ngừng sử dụng')], default='active', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
            },
        ),
        migrations.CreateModel(
            name='NDTMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phương pháp')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã phương pháp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phương pháp NDT',
                'verbose_name_plural': 'Phương pháp NDT',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã dự án')),
                ('description', models.TextField(verbose_name='Mô tả dự án')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('planning', 'Lập kế hoạch'), ('active', 'Đang thực hiện'), ('pending', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='planning', max_length=20, verbose_name='Trạng thái')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Giá trị hợp đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company', verbose_name='Công ty')),
                ('equipment', models.ManyToManyField(to='api.equipment', verbose_name='Thiết bị sử dụng')),
                ('methods', models.ManyToManyField(to='api.ndtmethod', verbose_name='Phương pháp NDT')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Quản lý dự án')),
                ('staff', models.ManyToManyField(related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('word', 'Word'), ('image', 'Hình ảnh'), ('other', 'Khác')], max_length=20, verbose_name='Loại file')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian upload')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project', verbose_name='Dự án')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'File dự án',
                'verbose_name_plural': 'File dự án',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.PositiveIntegerField(default=0, verbose_name='Phần trăm hoàn thành')),
                ('milestones_completed', models.PositiveIntegerField(default=0, verbose_name='Cột mốc hoàn thành')),
                ('total_milestones', models.PositiveIntegerField(default=0, verbose_name='Tổng cột mốc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Tiến độ dự án',
                'verbose_name_plural': 'Tiến độ dự án',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Số báo cáo')),
                ('test_date', models.DateField(verbose_name='Ngày kiểm tra')),
                ('test_location', models.CharField(max_length=200, verbose_name='Vị trí kiểm tra')),
                ('test_results', models.TextField(verbose_name='Kết quả kiểm tra')),
                ('defects_found', models.TextField(blank=True, verbose_name='Khuyết tật phát hiện')),
                ('recommendations', models.TextField(blank=True, verbose_name='Khuyến nghị')),
                ('report_file', models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='File báo cáo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_used', models.ManyToManyField(to='api.equipment', verbose_name='Thiết bị sử dụng')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm tra')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ndtmethod', verbose_name='Phương pháp')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Báo cáo kiểm tra',
                'verbose_name_plural': 'Báo cáo kiểm tra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThicknessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_point', models.CharField(max_length=100, verbose_name='Điểm đo')),
                ('thickness_value', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Giá trị độ dày (mm)')),
                ('minimum_thickness', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Độ dày tối thiểu (mm)')),
                ('measurement_date', models.DateTimeField(verbose_name='Thời gian đo')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nhiệt độ (°C)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment', verbose_name='Thiết bị đo')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Dữ liệu độ dày',
                'verbose_name_plural': 'Dữ liệu độ dày',
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='WeldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weld_id', models.CharField(max_length=100, verbose_name='Mã mối hàn')),
                ('weld_type', models.CharField(max_length=50, verbose_name='Loại mối hàn')),
                ('material', models.CharField(max_length=100, verbose_name='Vật liệu')),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Độ dày (mm)')),
                ('welding_process', models.CharField(max_length=50, verbose_name='Quy trình hàn')),
                ('test_date', models.DateField(verbose_name='Ngày kiểm tra')),
                ('result', models.CharField(choices=[('accept', 'Đạt'), ('reject', 'Không đạt'), ('repair', 'Cần sửa chữa')], max_length=20, verbose_name='Kết quả')),
                ('defect_description', models.TextField(blank=True, verbose_name='Mô tả khuyết tật')),
                ('repair_required', models.BooleanField(default=False, verbose_name='Cần sửa chữa')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm tra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='Dự án')),
                ('test_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ndtmethod', verbose_name='Phương pháp kiểm tra')),
            ],
            options={
                'verbose_name': 'Dữ liệu mối hàn',
                'verbose_name_plural': 'Dữ liệu mối hàn',
                'ordering': ['-test_date'],
            },
        ),
    ]
