# Generated by Django 4.2.7 on 2025-06-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_company_equipment_ndtmethod_project_projectfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Chuyên mục dịch vụ', 'verbose_name_plural': 'Chuyên mục dịch vụ'},
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta Title'),
        ),
    ]
