# Generated by Django 4.2.7 on 2025-06-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
