# Generated by Django 4.2.7 on 2025-06-24 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tài liệu')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='File tài liệu')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('xls', 'Excel'), ('xlsx', 'Excel (XLSX)'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint (PPTX)'), ('txt', 'Text'), ('image', 'Hình ảnh'), ('video', 'Video'), ('zip', 'Archive'), ('other', 'Khác')], max_length=20, verbose_name='Loại file')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kích thước file (bytes)')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Phiên bản')),
                ('document_code', models.CharField(max_length=50, unique=True, verbose_name='Mã tài liệu')),
                ('access_level', models.CharField(choices=[('public', 'Công khai'), ('internal', 'Nội bộ'), ('restricted', 'Hạn chế'), ('confidential', 'Bí mật')], default='internal', max_length=20, verbose_name='Mức độ truy cập')),
                ('allowed_roles', models.CharField(blank=True, help_text='Các vai trò được phép truy cập (admin,manager,staff)', max_length=100, verbose_name='Vai trò được phép')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('review', 'Đang xem xét'), ('approved', 'Đã phê duyệt'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phê duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt tải')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt xem')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Màu hiển thị')),
            ],
            options={
                'verbose_name': 'Tag tài liệu',
                'verbose_name_plural': 'Tag tài liệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Icon FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.documentcategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục tài liệu',
                'verbose_name_plural': 'Danh mục tài liệu',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Xem'), ('download', 'Tải xuống'), ('share', 'Chia sẻ')], max_length=20, verbose_name='Hành động')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian truy cập')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.document', verbose_name='Tài liệu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử truy cập',
                'verbose_name_plural': 'Lịch sử truy cập',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.documentcategory', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.documenttag', verbose_name='Thẻ tags'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='Số phiên bản')),
                ('file', models.FileField(upload_to='document_versions/%Y/%m/%d/', verbose_name='File phiên bản')),
                ('change_log', models.TextField(verbose_name='Nhật ký thay đổi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.document', verbose_name='Tài liệu')),
            ],
            options={
                'verbose_name': 'Phiên bản tài liệu',
                'verbose_name_plural': 'Phiên bản tài liệu',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'version')},
            },
        ),
    ]
