# Generated by Django 4.2.7 on 2025-06-25 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_document_documenttag_documentcategory_documentaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật cuối'),
        ),
    ]
