# Generated by Django 4.2.7 on 2025-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_document_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/hero/', verbose_name='Ảnh nền Hero Section'),
        ),
    ]
