# Generated by Django 4.2.7 on 2025-06-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_aboutpage_hero_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/timeline/', verbose_name='Ảnh nền phần Lịch sử phát triển'),
        ),
    ]
