# Generated by Django 4.2.7 on 2025-06-25 05:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_aboutpage_timeline_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Nội dung chi tiết'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Xuất bản'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Tóm tắt dự án'),
        ),
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem'),
        ),
    ]
