# Generated by Django 4.2.7 on 2025-06-25 05:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_project_content_project_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dự án (Nội bộ)', 'verbose_name_plural': 'Dự án (Nội bộ)'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='view_count',
        ),
        migrations.CreateModel(
            name='PublicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề dự án')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='public_projects/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('summary', models.TextField(verbose_name='Tóm tắt dự án')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Nội dung chi tiết')),
                ('client_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm')),
                ('project_type', models.CharField(max_length=100, verbose_name='Loại dự án')),
                ('completion_date', models.DateField(verbose_name='Ngày hoàn thành')),
                ('project_value', models.CharField(blank=True, max_length=100, verbose_name='Giá trị dự án (text)')),
                ('tags', models.CharField(blank=True, help_text='Các tag cách nhau bằng dấu phẩy', max_length=200, verbose_name='Tags')),
                ('status', models.CharField(choices=[('completed', 'Hoàn thành'), ('ongoing', 'Đang thực hiện'), ('featured', 'Nổi bật')], default='completed', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Dự án nổi bật')),
                ('published', models.BooleanField(default=True, verbose_name='Xuất bản')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Dự án công khai',
                'verbose_name_plural': 'Dự án công khai',
                'ordering': ['-created_at'],
            },
        ),
    ]
