# Generated by Django 4.2.7 on 2025-06-25 07:07

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_project_options_remove_project_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='achievements_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Thành tựu'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='achievements_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/achievements/', verbose_name='Ảnh phần Thành tựu'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='achievements_title',
            field=models.CharField(default='Thành tựu & Chứng nhận', max_length=200, verbose_name='Tiêu đề phần Thành tựu'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_color',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ nội dung'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_font_family',
            field=models.CharField(default='Open Sans, sans-serif', max_length=100, verbose_name='Font chữ nội dung'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certificates_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Chứng chỉ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certificates_section_subtitle',
            field=models.TextField(blank=True, verbose_name='Mô tả phần Chứng chỉ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='container_max_width',
            field=models.CharField(default='1200px', max_length=20, verbose_name='Chiều rộng tối đa container'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_bg_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nút CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button_text',
            field=models.CharField(default='Liên hệ ngay', max_length=50, verbose_name='Văn bản nút CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button_text_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ nút CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_button_url',
            field=models.CharField(default='/lien-he/', max_length=200, verbose_name='Liên kết nút CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_subtitle',
            field=models.TextField(default='Liên hệ với chúng tôi ngay hôm nay để được tư vấn miễn phí', verbose_name='Mô tả CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ CTA'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_title',
            field=models.CharField(default='Sẵn sàng hợp tác?', max_length=200, verbose_name='Tiêu đề Call to Action'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='heading_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Màu tiêu đề chính'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='heading_font_family',
            field=models.CharField(default='Roboto, sans-serif', max_length=100, verbose_name='Font chữ tiêu đề'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_bg_color',
            field=colorfield.fields.ColorField(default='#003d99', image_field=None, max_length=25, samples=None, verbose_name='Màu nền Hero (khi không có ảnh)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần nội dung chính'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_content',
            field=ckeditor.fields.RichTextField(default='<p>Hitech NDT là đơn vị hàng đầu trong lĩnh vực kiểm tra không phá hủy tại Việt Nam. Với đội ngũ kỹ sư giàu kinh nghiệm và trang thiết bị hiện đại, chúng tôi cam kết mang đến những dịch vụ chất lượng cao nhất cho khách hàng.</p>', help_text='Nội dung giới thiệu chính về công ty', verbose_name='Nội dung chính'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ảnh chính'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_title',
            field=models.CharField(default='Công ty của chúng tôi', max_length=200, verbose_name='Tiêu đề chính'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_color',
            field=colorfield.fields.ColorField(default='#28a745', image_field=None, max_length=25, samples=None, verbose_name='Màu chủ đạo Sứ mệnh'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_icon',
            field=models.CharField(default='fas fa-bullseye', max_length=50, verbose_name='Icon Sứ mệnh'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='Sứ mệnh', max_length=100, verbose_name='Tiêu đề Sứ mệnh'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='section_padding',
            field=models.CharField(default='80px 0', max_length=20, verbose_name='Padding cho các section'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Danh sách các dịch vụ/năng lực chính', null=True, verbose_name='Nội dung phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services_subtitle',
            field=models.TextField(blank=True, verbose_name='Mô tả phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services_title',
            field=models.CharField(default='Dịch vụ của chúng tôi', max_length=200, verbose_name='Tiêu đề phần Dịch vụ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat1_icon',
            field=models.CharField(default='fas fa-project-diagram', max_length=50, verbose_name='Icon số liệu 1 (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat1_label',
            field=models.CharField(default='Dự án hoàn thành', max_length=100, verbose_name='Nhãn số liệu 1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat1_number',
            field=models.CharField(default='500+', max_length=20, verbose_name='Số liệu 1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat2_icon',
            field=models.CharField(default='fas fa-calendar-alt', max_length=50, verbose_name='Icon số liệu 2 (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat2_label',
            field=models.CharField(default='Năm kinh nghiệm', max_length=100, verbose_name='Nhãn số liệu 2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat2_number',
            field=models.CharField(default='15+', max_length=20, verbose_name='Số liệu 2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat3_icon',
            field=models.CharField(default='fas fa-handshake', max_length=50, verbose_name='Icon số liệu 3 (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat3_label',
            field=models.CharField(default='Khách hàng tin tưởng', max_length=100, verbose_name='Nhãn số liệu 3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat3_number',
            field=models.CharField(default='100+', max_length=20, verbose_name='Số liệu 3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat4_icon',
            field=models.CharField(default='fas fa-clock', max_length=50, verbose_name='Icon số liệu 4 (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat4_label',
            field=models.CharField(default='Hỗ trợ khách hàng', max_length=100, verbose_name='Nhãn số liệu 4'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat4_number',
            field=models.CharField(default='24/7', max_length=20, verbose_name='Số liệu 4'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần thống kê'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ phần thống kê'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stats_title',
            field=models.CharField(default='Con số ấn tượng', max_length=200, verbose_name='Tiêu đề phần thống kê'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Đội ngũ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Ảnh nền phần Đội ngũ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_accent_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Màu nhấn Timeline (đường kẻ, điểm)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Timeline'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_section_subtitle',
            field=models.TextField(blank=True, help_text='Mô tả ngắn về phần lịch sử phát triển', verbose_name='Mô tả phần cột mốc'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Màu chữ Timeline'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_color',
            field=colorfield.fields.ColorField(default='#ffc107', image_field=None, max_length=25, samples=None, verbose_name='Màu chủ đạo Giá trị cốt lõi'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_icon',
            field=models.CharField(default='fas fa-gem', max_length=50, verbose_name='Icon Giá trị cốt lõi'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(default='Giá trị cốt lõi', max_length=100, verbose_name='Tiêu đề Giá trị cốt lõi'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Màu chủ đạo Tầm nhìn'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_icon',
            field=models.CharField(default='fas fa-eye', max_length=50, verbose_name='Icon Tầm nhìn'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_title',
            field=models.CharField(default='Tầm nhìn', max_length=100, verbose_name='Tiêu đề Tầm nhìn'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vmv_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần VMV'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vmv_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/vmv/', verbose_name='Ảnh nền phần VMV'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vmv_title',
            field=models.CharField(default='Tầm nhìn - Sứ mệnh - Giá trị', max_length=200, verbose_name='Tiêu đề phần VMV'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='achievements',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung Thành tựu'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ảnh banner chính'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='certificates',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung Chứng chỉ'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Trường này để tương thích, khuyến khích dùng main_content', null=True, verbose_name='Nội dung cũ (tương thích)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='core_values',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung Giá trị cốt lõi'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung Sứ mệnh'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Phụ đề hiển thị bên dưới tiêu đề chính', max_length=300, verbose_name='Phụ đề'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='timeline_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/timeline/', verbose_name='Ảnh nền phần Timeline'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='Về Chúng Tôi', max_length=200, verbose_name='Tiêu đề trang'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung Tầm nhìn'),
        ),
    ]
