# Generated by Django 4.2.7 on 2025-06-25 08:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_aboutpage_achievements_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_overlay_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu overlay Timeline (khi có ảnh nền)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.95, help_text='0.0 = hoàn toàn trong suốt, 1.0 = hoàn toàn mờ', max_digits=3, verbose_name='Độ mờ overlay Timeline (0.0-1.0)'),
        ),
    ]
