# Generated by Django 4.2.7 on 2025-06-25 11:03

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_add_timeline_overlay_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='HITECH NDT', max_length=200, verbose_name='Tiêu đề Hero')),
                ('hero_subtitle', models.TextField(default='Giải pháp kiểm tra không phá hủy hàng đầu Việt Nam', verbose_name='Phụ đề Hero')),
                ('hero_bg_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/', verbose_name='Ảnh nền Hero')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#003d99', image_field=None, max_length=25, samples=None, verbose_name='Màu nền Hero (khi không có ảnh)')),
                ('hero_btn_primary_text', models.CharField(default='Khám phá dịch vụ', max_length=50, verbose_name='Nút chính - Text')),
                ('hero_btn_primary_url', models.CharField(default='/dich-vu/', max_length=100, verbose_name='Nút chính - URL')),
                ('hero_btn_secondary_text', models.CharField(default='Liên hệ ngay', max_length=50, verbose_name='Nút phụ - Text')),
                ('hero_btn_secondary_url', models.CharField(default='/lien-he/', max_length=100, verbose_name='Nút phụ - URL')),
                ('ndt_section_title', models.CharField(default='Phương pháp NDT chuyên nghiệp', max_length=200, verbose_name='Tiêu đề phần Phương pháp NDT')),
                ('ndt_section_subtitle', models.TextField(default='Ứng dụng các công nghệ kiểm tra không phá hủy tiên tiến nhất', verbose_name='Phụ đề phần NDT')),
                ('ndt_bg_color', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần NDT')),
                ('projects_section_title', models.CharField(default='Dự án nổi bật', max_length=200, verbose_name='Tiêu đề phần Dự án')),
                ('projects_section_subtitle', models.TextField(default='Những dự án tiêu biểu đã thực hiện thành công', verbose_name='Phụ đề phần Dự án')),
                ('projects_bg_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Dự án')),
                ('blog_section_title', models.CharField(default='Tin tức & Bài viết', max_length=200, verbose_name='Tiêu đề phần Blog')),
                ('blog_section_subtitle', models.TextField(default='Cập nhật những thông tin mới nhất về công nghệ NDT', verbose_name='Phụ đề phần Blog')),
                ('blog_bg_color', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Blog')),
                ('services_section_title', models.CharField(default='Dịch vụ chuyên nghiệp', max_length=200, verbose_name='Tiêu đề phần Dịch vụ')),
                ('services_section_subtitle', models.TextField(default='Giải pháp toàn diện cho mọi nhu cầu kiểm tra và đào tạo', verbose_name='Phụ đề phần Dịch vụ')),
                ('services_bg_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Dịch vụ')),
                ('testimonials_section_title', models.CharField(default='Khách hàng nói về chúng tôi', max_length=200, verbose_name='Tiêu đề phần Testimonials')),
                ('testimonials_section_subtitle', models.TextField(default='Phản hồi từ những khách hàng đã tin tưởng sử dụng dịch vụ', verbose_name='Phụ đề phần Testimonials')),
                ('testimonials_bg_color', colorfield.fields.ColorField(default='#667eea', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Testimonials')),
                ('partners_section_title', models.CharField(default='Đối tác tin cậy', max_length=200, verbose_name='Tiêu đề phần Đối tác')),
                ('partners_section_subtitle', models.TextField(default='Được tin tưởng bởi các doanh nghiệp hàng đầu trong và ngoài nước', verbose_name='Phụ đề phần Đối tác')),
                ('partners_bg_color', colorfield.fields.ColorField(default='#f5f7fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Đối tác')),
                ('trust_stat1_number', models.CharField(default='100+', max_length=20, verbose_name='Số liệu tin cậy 1')),
                ('trust_stat1_label', models.CharField(default='Đối tác tin cậy', max_length=100, verbose_name='Nhãn số liệu 1')),
                ('trust_stat2_number', models.CharField(default='500+', max_length=20, verbose_name='Số liệu tin cậy 2')),
                ('trust_stat2_label', models.CharField(default='Dự án thành công', max_length=100, verbose_name='Nhãn số liệu 2')),
                ('trust_stat3_number', models.CharField(default='15+', max_length=20, verbose_name='Số liệu tin cậy 3')),
                ('trust_stat3_label', models.CharField(default='Năm kinh nghiệm', max_length=100, verbose_name='Nhãn số liệu 3')),
                ('trust_stat4_number', models.CharField(default='24/7', max_length=20, verbose_name='Số liệu tin cậy 4')),
                ('trust_stat4_label', models.CharField(default='Hỗ trợ khách hàng', max_length=100, verbose_name='Nhãn số liệu 4')),
                ('why_section_title', models.CharField(default='Vì sao chọn Hitech NDT?', max_length=200, verbose_name='Tiêu đề phần Vì sao chọn')),
                ('why_section_subtitle', models.TextField(default='Những giá trị cốt lõi làm nên thương hiệu Hitech NDT', verbose_name='Phụ đề phần Vì sao chọn')),
                ('why_bg_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Vì sao chọn')),
                ('feature1_title', models.CharField(default='Chuyên nghiệp', max_length=100, verbose_name='Tính năng 1 - Tiêu đề')),
                ('feature1_description', models.TextField(default='Đội ngũ kỹ sư có chứng chỉ quốc tế và kinh nghiệm thực tiễn', verbose_name='Tính năng 1 - Mô tả')),
                ('feature1_icon', models.CharField(default='fas fa-medal', max_length=50, verbose_name='Tính năng 1 - Icon')),
                ('feature2_title', models.CharField(default='Công nghệ tiên tiến', max_length=100, verbose_name='Tính năng 2 - Tiêu đề')),
                ('feature2_description', models.TextField(default='Trang thiết bị hiện đại nhập khẩu từ các nước phát triển', verbose_name='Tính năng 2 - Mô tả')),
                ('feature2_icon', models.CharField(default='fas fa-rocket', max_length=50, verbose_name='Tính năng 2 - Icon')),
                ('feature3_title', models.CharField(default='Nhanh chóng', max_length=100, verbose_name='Tính năng 3 - Tiêu đề')),
                ('feature3_description', models.TextField(default='Thời gian thực hiện nhanh, báo cáo kết quả chính xác', verbose_name='Tính năng 3 - Mô tả')),
                ('feature3_icon', models.CharField(default='fas fa-clock', max_length=50, verbose_name='Tính năng 3 - Icon')),
                ('feature4_title', models.CharField(default='Tin cậy', max_length=100, verbose_name='Tính năng 4 - Tiêu đề')),
                ('feature4_description', models.TextField(default='Được hàng trăm khách hàng lớn tin tưởng và hợp tác lâu dài', verbose_name='Tính năng 4 - Mô tả')),
                ('feature4_icon', models.CharField(default='fas fa-handshake', max_length=50, verbose_name='Tính năng 4 - Icon')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('show_ndt_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Phương pháp NDT')),
                ('show_projects_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Dự án')),
                ('show_blog_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Blog')),
                ('show_services_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Dịch vụ')),
                ('show_testimonials_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Testimonials')),
                ('show_partners_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Đối tác')),
                ('show_why_section', models.BooleanField(default=True, verbose_name='Hiển thị phần Vì sao chọn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật cuối')),
            ],
            options={
                'verbose_name': 'Cấu hình trang chủ',
                'verbose_name_plural': 'Cấu hình trang chủ',
            },
        ),
    ]
