# Generated by Django 4.2.7 on 2025-06-25 11:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='ndt_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/sections/', verbose_name='Ảnh nền phần NDT'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='ndt_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.85, max_digits=3, verbose_name='Độ mờ overlay NDT (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner10_icon',
            field=models.CharField(default='fas fa-flask', max_length=50, verbose_name='Đối tác 10 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner10_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 10 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner10_name',
            field=models.CharField(default='SABIC', max_length=100, verbose_name='Đối tác 10 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner11_icon',
            field=models.CharField(default='fas fa-oil-can', max_length=50, verbose_name='Đối tác 11 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner11_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 11 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner11_name',
            field=models.CharField(default='Chevron', max_length=100, verbose_name='Đối tác 11 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner12_icon',
            field=models.CharField(default='fas fa-bolt', max_length=50, verbose_name='Đối tác 12 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner12_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 12 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner12_name',
            field=models.CharField(default='General Electric', max_length=100, verbose_name='Đối tác 12 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner1_icon',
            field=models.CharField(default='fas fa-industry', max_length=50, verbose_name='Đối tác 1 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 1 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner1_name',
            field=models.CharField(default='PetroVietnam', max_length=100, verbose_name='Đối tác 1 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner2_icon',
            field=models.CharField(default='fas fa-mobile-alt', max_length=50, verbose_name='Đối tác 2 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 2 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner2_name',
            field=models.CharField(default='Samsung', max_length=100, verbose_name='Đối tác 2 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner3_icon',
            field=models.CharField(default='fas fa-industry', max_length=50, verbose_name='Đối tác 3 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner3_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 3 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner3_name',
            field=models.CharField(default='Hòa Phát', max_length=100, verbose_name='Đối tác 3 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner4_icon',
            field=models.CharField(default='fas fa-building', max_length=50, verbose_name='Đối tác 4 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner4_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 4 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner4_name',
            field=models.CharField(default='Vingroup', max_length=100, verbose_name='Đối tác 4 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner5_icon',
            field=models.CharField(default='fas fa-laptop-code', max_length=50, verbose_name='Đối tác 5 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner5_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 5 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner5_name',
            field=models.CharField(default='FPT', max_length=100, verbose_name='Đối tác 5 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner6_icon',
            field=models.CharField(default='fas fa-satellite-dish', max_length=50, verbose_name='Đối tác 6 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner6_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 6 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner6_name',
            field=models.CharField(default='Viettel', max_length=100, verbose_name='Đối tác 6 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner7_icon',
            field=models.CharField(default='fas fa-hammer', max_length=50, verbose_name='Đối tác 7 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner7_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 7 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner7_name',
            field=models.CharField(default='VNSteel', max_length=100, verbose_name='Đối tác 7 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner8_icon',
            field=models.CharField(default='fas fa-motorcycle', max_length=50, verbose_name='Đối tác 8 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner8_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 8 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner8_name',
            field=models.CharField(default='Honda', max_length=100, verbose_name='Đối tác 8 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner9_icon',
            field=models.CharField(default='fas fa-car', max_length=50, verbose_name='Đối tác 9 - Icon (fallback)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner9_logo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/partners/', verbose_name='Đối tác 9 - Logo'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partner9_name',
            field=models.CharField(default='Toyota', max_length=100, verbose_name='Đối tác 9 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partners_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/sections/', verbose_name='Ảnh nền phần Đối tác'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partners_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.95, max_digits=3, verbose_name='Độ mờ overlay Đối tác (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/sections/', verbose_name='Ảnh nền phần Testimonials'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=3, verbose_name='Độ mờ overlay Testimonials (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='ndt_bg_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần NDT (khi không có ảnh)'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='partners_bg_color',
            field=colorfield.fields.ColorField(default='#f5f7fa', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Đối tác (khi không có ảnh)'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='testimonials_bg_color',
            field=colorfield.fields.ColorField(default='#667eea', image_field=None, max_length=25, samples=None, verbose_name='Màu nền phần Testimonials (khi không có ảnh)'),
        ),
    ]
