# Generated by Django 4.2.7 on 2025-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_homepagesettings_ndt_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial1_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/', verbose_name='Testimonial 1 - Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial1_company',
            field=models.CharField(default='Công ty TNHH ABC', max_length=100, verbose_name='Testimonial 1 - Công ty'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial1_content',
            field=models.TextField(default='Hitech NDT đã cung cấp dịch vụ kiểm tra chất lượng cao cho dự án của chúng tôi. Đội ngũ chuyên nghiệp, thiết bị hiện đại và báo cáo chi tiết, chính xác.', verbose_name='Testimonial 1 - Nội dung'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial1_name',
            field=models.CharField(default='Trần Văn Long', max_length=100, verbose_name='Testimonial 1 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial1_position',
            field=models.CharField(default='Trưởng phòng kỹ thuật', max_length=100, verbose_name='Testimonial 1 - Chức vụ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial2_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/', verbose_name='Testimonial 2 - Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial2_company',
            field=models.CharField(default='Tập đoàn Dầu khí Việt Nam', max_length=100, verbose_name='Testimonial 2 - Công ty'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial2_content',
            field=models.TextField(default='Dịch vụ đào tạo chứng chỉ NDT Level II tại Hitech rất chuyên nghiệp. Giáo viên giàu kinh nghiệm, tài liệu đầy đủ và thiết bị thực hành hiện đại.', verbose_name='Testimonial 2 - Nội dung'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial2_name',
            field=models.CharField(default='Nguyễn Thanh Huy', max_length=100, verbose_name='Testimonial 2 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial2_position',
            field=models.CharField(default='Kỹ sư NDT', max_length=100, verbose_name='Testimonial 2 - Chức vụ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial3_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/', verbose_name='Testimonial 3 - Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial3_company',
            field=models.CharField(default='Công ty Cơ khí XYZ', max_length=100, verbose_name='Testimonial 3 - Công ty'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial3_content',
            field=models.TextField(default='Hitech NDT luôn đáp ứng đúng tiến độ và chất lượng cam kết. Đây là đối tác tin cậy cho các dự án kiểm tra của chúng tôi.', verbose_name='Testimonial 3 - Nội dung'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial3_name',
            field=models.CharField(default='Mai Thị Thuỷ', max_length=100, verbose_name='Testimonial 3 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial3_position',
            field=models.CharField(default='Giám đốc kỹ thuật', max_length=100, verbose_name='Testimonial 3 - Chức vụ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial4_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/', verbose_name='Testimonial 4 - Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial4_company',
            field=models.CharField(default='Nhà máy Thép Hòa Phát', max_length=100, verbose_name='Testimonial 4 - Công ty'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial4_content',
            field=models.TextField(default='Thiết bị kiểm tra được Hitech cung cấp rất hiện đại và chính xác. Hỗ trợ kỹ thuật 24/7 giúp chúng tôi yên tâm trong quá trình thực hiện dự án.', verbose_name='Testimonial 4 - Nội dung'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial4_name',
            field=models.CharField(default='Phạm Văn Dũng', max_length=100, verbose_name='Testimonial 4 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial4_position',
            field=models.CharField(default='Chuyên viên kiểm tra', max_length=100, verbose_name='Testimonial 4 - Chức vụ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial5_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/', verbose_name='Testimonial 5 - Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial5_company',
            field=models.CharField(default='Samsung Electronics Vietnam', max_length=100, verbose_name='Testimonial 5 - Công ty'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial5_content',
            field=models.TextField(default='Báo cáo kiểm tra từ Hitech luôn chi tiết, rõ ràng và đúng tiêu chuẩn quốc tế. Điều này giúp chúng tôi thuyết phục được khách hàng quốc tế.', verbose_name='Testimonial 5 - Nội dung'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial5_name',
            field=models.CharField(default='Lê Minh Khang', max_length=100, verbose_name='Testimonial 5 - Tên'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial5_position',
            field=models.CharField(default='QA Manager', max_length=100, verbose_name='Testimonial 5 - Chức vụ'),
        ),
    ]
