# Generated by Django 4.2.7 on 2025-06-27 15:51

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_testimonials_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='achievements',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nội dung Thành tựu'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='certificates',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nội dung Chứng chỉ'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Trường này để tương thích, khuyến khích dùng main_content', null=True, verbose_name='Nội dung cũ (tương thích)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='core_values',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nội dung Giá trị cốt lõi'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='main_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='<p>Hitech NDT là đơn vị hàng đầu trong lĩnh vực kiểm tra không phá hủy tại Việt Nam. Với đội ngũ kỹ sư giàu kinh nghiệm và trang thiết bị hiện đại, chúng tôi cam kết mang đến những dịch vụ chất lượng cao nhất cho khách hàng.</p>', help_text='Nội dung giới thiệu chính về công ty', verbose_name='Nội dung chính'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nội dung Sứ mệnh'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='services_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Danh sách các dịch vụ/năng lực chính', null=True, verbose_name='Nội dung phần Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_section_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Mô tả phần đội ngũ'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nội dung Tầm nhìn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='publicproject',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Nội dung chi tiết'),
        ),
    ]
