# Generated by Django 4.2.7 on 2025-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_aboutpage_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Mô tả hiển thị trên Google (tối đa 160 ký tự).', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Từ khóa SEO, phân cách bằng dấu phẩy.', max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Tiêu đề hiển thị trên Google (tối đa 60 ký tự). Để trống sẽ sử dụng tiêu đề bài viết.', max_length=60, null=True, verbose_name='Meta Title'),
        ),
    ]
