# Generated by Django 4.2.7 on 2025-06-30 08:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_post_meta_description_post_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_content',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='client_logo1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='client_logo2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='client_logo3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='client_logo4',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='client_logo5',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='client_logo6',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='clients_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='clients_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_bg_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_btn_primary_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_btn_primary_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_btn_secondary_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_btn_secondary_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='projects_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='projects_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='projects_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='testimonials_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='testimonials_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='danger_color',
            field=colorfield.fields.ColorField(default='#dc3545', image_field=None, max_length=25, samples=None, verbose_name='Màu nguy hiểm (Danger)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_floating_contact',
            field=models.BooleanField(default=True, verbose_name='Bật liên hệ nhanh (floating)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='floating_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT liên hệ nhanh'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='floating_zalo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số Zalo liên hệ nhanh'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(default='Roboto, sans-serif', max_length=100, verbose_name='Font chữ chính'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2024 Hitech NDT. Tất cả quyền được bảo lưu.', max_length=200, verbose_name='Bản quyền Footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(default='Roboto, sans-serif', max_length=100, verbose_name='Font chữ tiêu đề'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_sticky',
            field=models.BooleanField(default=True, verbose_name='Navbar dính (sticky)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Màu chính (Primary)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None, verbose_name='Màu phụ (Secondary)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='Hiển thị breadcrumb (đường dẫn)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_scroll_top',
            field=models.BooleanField(default=True, verbose_name='Hiển thị nút cuộn lên đầu trang'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='Công ty hàng đầu về kiểm tra không phá hủy (NDT) tại Việt Nam. Cung cấp dịch vụ chuyên nghiệp và đào tạo chứng chỉ NDT.', verbose_name='Mô tả website (Meta Description)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords',
            field=models.CharField(default='NDT, kiểm tra không phá hủy, Hitech NDT, chứng chỉ NDT', max_length=300, verbose_name='Từ khóa SEO'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Hitech NDT - Giải pháp kiểm tra không phá hủy', max_length=200, verbose_name='Tiêu đề website (Meta Title)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='success_color',
            field=colorfield.fields.ColorField(default='#28a745', image_field=None, max_length=25, samples=None, verbose_name='Màu thành công (Success)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warning_color',
            field=colorfield.fields.ColorField(default='#ffc107', image_field=None, max_length=25, samples=None, verbose_name='Màu cảnh báo (Warning)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zalo_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số Zalo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_address',
            field=models.CharField(default='123 Đường ABC, Quận XYZ, TP.HCM', max_length=200, verbose_name='Địa chỉ công ty'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_email',
            field=models.EmailField(default='info@hitechndt.com', max_length=254, verbose_name='Email liên hệ chính'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_phone',
            field=models.CharField(default='+84 123 456 789', max_length=20, verbose_name='Số điện thoại chính'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo công ty (hiển thị trên navbar)'),
        ),
    ]
