# Generated by Django 4.2.7 on 2025-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_update_sitesettings_for_general_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Cấu hình chung website', 'verbose_name_plural': 'Cấu hình chung website'},
        ),
        migrations.AddField(
            model_name='project',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Phần trăm hoàn thành'),
        ),
    ]
