# Generated by Django 4.2.7 on 2025-07-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='maps_link',
            field=models.URLField(blank=True, help_text='Link trực tiếp đến Google Maps (VD: https://maps.app.goo.gl/A8TcFmJHawaxYMND6)', null=True, verbose_name='Link Google Maps'),
        ),
    ]
