# Generated by Django 4.2.7 on 2025-07-28 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0036_add_maps_link_to_contact_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Nghỉ phép năm'), ('sick', 'Nghỉ ốm'), ('personal', 'Nghỉ việc riêng'), ('maternity', 'Nghỉ thai sản'), ('other', 'Khác')], max_length=20, verbose_name='Loại nghỉ phép')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('total_days', models.PositiveIntegerField(verbose_name='Tổng số ngày')),
                ('reason', models.TextField(verbose_name='Lý do nghỉ phép')),
                ('handover_tasks', models.TextField(blank=True, verbose_name='Công việc bàn giao')),
                ('status', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('final_decision_reason', models.TextField(blank=True, verbose_name='Lý do quyết định cuối cùng')),
                ('team_lead_approval', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Phê duyệt trưởng nhóm')),
                ('team_lead_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phê duyệt trưởng nhóm')),
                ('team_lead_rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối trưởng nhóm')),
                ('manager_approval', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Phê duyệt quản lý')),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phê duyệt quản lý')),
                ('manager_rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối quản lý')),
                ('company_approval', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Phê duyệt công ty')),
                ('company_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phê duyệt công ty')),
                ('company_rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối công ty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Công ty phê duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('handover_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người bàn giao')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý phê duyệt')),
                ('team_lead_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng nhóm phê duyệt')),
            ],
            options={
                'verbose_name': 'Yêu cầu nghỉ phép',
                'verbose_name_plural': 'Yêu cầu nghỉ phép',
                'ordering': ['-created_at'],
            },
        ),
    ]
