# Generated by Django 4.2.7 on 2025-07-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificates',
            field=models.TextField(blank=True, help_text='Danh sách chứng chỉ, mỗi chứng chỉ một dòng', null=True, verbose_name='Chứng chỉ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='api.project', verbose_name='Dự án hiện tại'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT khẩn cấp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_team_lead',
            field=models.BooleanField(default=False, verbose_name='Là trưởng nhóm'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tham gia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí công việc'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí trong dự án'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Danh sách kỹ năng, mỗi kỹ năng một dòng', null=True, verbose_name='Kỹ năng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('company', 'Công ty'), ('manager', 'Quản lý'), ('team_lead', 'Trưởng nhóm'), ('staff', 'Nhân viên')], default='staff', max_length=20, verbose_name='Vai trò'),
        ),
    ]
