# Generated by Django 4.2.7 on 2025-07-31 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0039_remove_team_lead_add_handover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày chấm công')),
                ('work_type', models.CharField(choices=[('W', 'Công trường'), ('O', 'Văn phòng'), ('T', 'Đào tạo'), ('P', 'Nghỉ có phép'), ('N', 'Nghỉ không phép')], max_length=1, verbose_name='Loại công việc')),
                ('construction_name', models.CharField(blank=True, max_length=200, verbose_name='Tên công trình')),
                ('ndt_method', models.CharField(blank=True, max_length=100, verbose_name='Phương pháp NDT')),
                ('day_shift', models.BooleanField(default=False, verbose_name='Ca ngày')),
                ('night_shift', models.BooleanField(default=False, verbose_name='Ca đêm')),
                ('day_overtime_end', models.TimeField(blank=True, null=True, verbose_name='Tăng ca ngày đến')),
                ('night_overtime_end', models.TimeField(blank=True, null=True, verbose_name='Tăng ca đêm đến')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Số giờ tăng ca')),
                ('hotel_expense', models.BooleanField(default=False, verbose_name='Chi phí khách sạn')),
                ('shopping_expense', models.BooleanField(default=False, verbose_name='Chi phí mua sắm')),
                ('phone_expense', models.BooleanField(default=False, verbose_name='Chi phí điện thoại')),
                ('other_expense', models.BooleanField(default=False, verbose_name='Chi phí khác')),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số tiền chi phí')),
                ('other_expense_desc', models.TextField(blank=True, verbose_name='Mô tả chi phí khác')),
                ('work_note', models.TextField(blank=True, verbose_name='Ghi chú công việc')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Tự động tạo từ yêu cầu nghỉ phép')),
                ('can_be_edited', models.BooleanField(default=True, verbose_name='Có thể chỉnh sửa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='api.leaverequest', verbose_name='Yêu cầu nghỉ phép liên quan')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật cuối')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
