# Generated by Django 4.2.7 on 2025-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='expense_amount',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hotel_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chi phí khách sạn (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='other_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chi phí khác (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='phone_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chi phí điện thoại (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shopping_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chi phí mua sắm (VNĐ)'),
        ),
    ]
