# Generated by Django 4.2.7 on 2025-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_attendance_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='paut_meters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Số mét vượt PAUT'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tofd_meters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Số mét vượt TOFD'),
        ),
    ]
