# Generated by Django 4.2.7 on 2025-08-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_attendance_paut_meters_attendance_tofd_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='msnv',
            field=models.CharField(blank=True, help_text='Mã số nhân viên duy nhất', max_length=20, null=True, verbose_name='Mã số nhân viên'),
        ),
    ]
