# Generated by Django 4.2.7 on 2025-09-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userprofile_msnv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
