# Generated by Django 4.2.7 on 2025-09-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_attendance_unique_constraint'),
        ('api', '0045_update_document_model'),
        ('api', '0048_create_document_access_log'),
    ]

    operations = [
    ]
