# Generated by Django 4.2.7 on 2025-09-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_file_type_field'),
        ('api', '0049_merge_20250915_1005'),
    ]

    operations = [
    ]
