# Generated by Django 4.2.7 on 2025-09-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_add_access_level_state'),
    ]

    operations = [
    ]
