# Generated by Django 4.2.7 on 2025-09-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_access_level_state'),
        ('api', '0052_add_allowed_roles_state'),
    ]

    operations = [
    ]
