# Generated by Django 4.2.7 on 2025-09-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_status_state'),
        ('api', '0053_merge_20250915_1353'),
    ]

    operations = [
    ]
