# Generated by Django 4.2.7 on 2025-09-16 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0054_merge_0053_add_status_state_0053_merge_20250915_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Phải đổi mật khẩu lần đầu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_set_email',
            field=models.BooleanField(default=True, verbose_name='Phải bổ sung email lần đầu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_last_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần đổi mật khẩu gần nhất'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.documenttag'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('parent_document', 'version')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
    ]
