# Generated by Django 4.2.7 on 2025-09-16 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0055_alter_document_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_files/%Y/%m/%d/', verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file_size', models.BigIntegerField(verbose_name='Kích thước file')),
                ('file_type', models.CharField(max_length=50, verbose_name='Loại file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian upload')),
                ('is_current', models.BooleanField(default=False, verbose_name='File hiện tại')),
                ('change_note', models.TextField(blank=True, verbose_name='Ghi chú thay đổi')),
                ('version_number', models.PositiveIntegerField(verbose_name='Số phiên bản')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='api.document', verbose_name='Tài liệu')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Phiên bản file tài liệu',
                'verbose_name_plural': 'Phiên bản file tài liệu',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
