# Generated by Django 4.2.7 on 2025-09-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_documentfileversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên đối tác/khách hàng')),
                ('logo', models.ImageField(upload_to='about/partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, verbose_name='Website (tuỳ chọn)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='api.aboutpage', verbose_name='Trang giới thiệu')),
            ],
            options={
                'verbose_name': 'Đối tác/Khách hàng',
                'verbose_name_plural': 'Đối tác/Khách hàng',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.aboutpage', verbose_name='Trang giới thiệu')),
            ],
            options={
                'verbose_name': 'Ảnh gallery',
                'verbose_name_plural': 'Ảnh gallery',
                'ordering': ['order', 'id'],
            },
        ),
    ]
