# Generated by Django 4.2.7 on 2025-09-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_aboutpartner_aboutgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImageStripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/strip/', verbose_name='Ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Alt text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_strip_items', to='api.aboutpage', verbose_name='Trang giới thiệu')),
            ],
            options={
                'verbose_name': 'Ảnh dải strip',
                'verbose_name_plural': 'Ảnh dải strip',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tiêu đề')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('image', models.ImageField(upload_to='about/features/', verbose_name='Ảnh')),
                ('link_url', models.URLField(blank=True, verbose_name='Liên kết (tuỳ chọn)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.aboutpage', verbose_name='Trang giới thiệu')),
            ],
            options={
                'verbose_name': 'Năng lực/Thế mạnh',
                'verbose_name_plural': 'Năng lực/Thế mạnh',
                'ordering': ['order', 'id'],
            },
        ),
    ]
