# Generated by Django 4.2.7 on 2025-09-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_aboutimagestripitem_aboutfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutgalleryimage',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='aboutimagestripitem',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='aboutpartner',
            name='about_page',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Technician'), ('employee_rd', 'R&D Technician'), ('manager', 'Site Manager'), ('company', 'Technical Manager'), ('team_lead', 'NDT Team Leader')], default='employee', max_length=50),
        ),
        migrations.DeleteModel(
            name='AboutFeature',
        ),
        migrations.DeleteModel(
            name='AboutGalleryImage',
        ),
        migrations.DeleteModel(
            name='AboutImageStripItem',
        ),
        migrations.DeleteModel(
            name='AboutPartner',
        ),
    ]
