# Generated by Django 4.2.7 on 2025-09-18 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_aboutgalleryimage_about_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cccd', models.CharField(blank=True, max_length=20, null=True)),
                ('msnv', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(choices=[('employee', 'Technician'), ('employee_rd', 'R&D Technician'), ('manager', 'Site Manager'), ('company', 'Technical Manager'), ('team_lead', 'NDT Team Leader')], default='employee', max_length=50)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('project_position', models.CharField(blank=True, max_length=100, null=True)),
                ('certificates', models.TextField(blank=True, null=True)),
                ('avatar_data_url', models.TextField(blank=True, help_text='Ảnh base64 từ client', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['-updated_at'],
            },
        ),
    ]
