# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('logo_hitech.png', '.'),
        ('logo_hitech.ico', '.'),
        ('sample_chamcong.csv', '.'),
        ('data/', 'data/'),
        ('backup/', 'backup/'),
    ],
    hiddenimports=[
        'PyQt5.QtCore',
        'PyQt5.QtGui', 
        'PyQt5.QtWidgets',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.backends.backend_qt5agg',
        'numpy',
        'pandas',
        'json',
        'os',
        'sys',
        'datetime',
        'csv',
        'data_manager',
        'bang_cong',
        'phieu_luong', 
        'tong_luong',
        'nhanvien',
        'quy_dinh_luong',
        'new_company_dialog',
        'company_matcher',
        'formula_tooltip'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Hitech_ChamCong',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['logo_hitech.ico'],
) 